Add colors
LabyMod/og-names pull request #140
Opened 2023-03-12 15:07 UTC by e6

Added `colors` folder with `colors.txt`, a list of all colors. 

These are considered as OG usernames.

2023-03-12 23:15 UTC, l3nnartt commented
I guess it would be better to put Giselle and the colors in separate PRs

2023-03-13 04:17 UTC, Kalsie requested changes
Kalsie shouldn't be removed especially after it's already received approval.

2023-03-13 08:45 UTC, Dqnns commented
Kalsie is a common first name in the USA, I don’t see why it should get
reverted.

Kalsie ***@***.***> schrieb am Mo. 13. März 2023 um 05:17:

> ***@***.**** requested changes on this pull request.
>
> Kalsie shouldn't be removed especially after it's already received
> approval.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/LabyMod/og-names/pull/140#pullrequestreview-1336224314>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW3SHP2Q2ZI4P2H3LA4RCZ3W32UVXANCNFSM6AAAAAAVYFKVTQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-03-27 18:10 UTC, l3nnartt requested changes

2023-03-27 18:10 UTC, l3nnartt commented on src/names/names.txt
> +Giselle
You should still put Giselle in a separate pr

2024-04-28 00:50 UTC, Dqnns commented
run cleanup.py

2024-09-13 12:45 UTC, closed without merging