Remove semis from verbs.txt
LabyMod/og-names pull request #40
Opened 2022-03-19 13:15 UTC by Dqnns

Removed unnecessary nouns and deleted a few 2 character usernames.

2022-04-19 00:39 UTC, bribes commented
> This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

rip

2022-04-19 19:14 UTC, bribes commented
Nathaniel is a real name.

2022-04-19 22:28 UTC, bribes commented on src/names/names.txt
> -Nathaniel
Nathaniel is a real name.

2022-04-19 22:29 UTC, bribes requested changes
Nathaniel is a real name that is used IRL.

2022-04-19 22:31 UTC, bribes commented on src/names/names.txt
> -Nathaniel
Nathaniel is a real name.

2022-04-20 05:53 UTC, Dqnns commented
> 

Great, thanks ^^

2023-01-20 12:47 UTC, closed without merging